# Generated by Django 4.2 on 2025-07-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoistureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField(unique=True)),
                ('sensor_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('soil_moisture_percent', models.FloatField()),
                ('temperature_celsius', models.FloatField()),
                ('humidity_percent', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('battery_voltage', models.FloatField()),
                ('irrigation_action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'soil_moisture_records',
            },
        ),
    ]
