# Generated by Django 4.2 on 2025-07-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_soilmoisturerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilMoisturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=100)),
                ('predicted_moisture', models.FloatField()),
                ('input_moisture', models.FloatField()),
                ('input_temperature', models.FloatField()),
                ('input_humidity', models.FloatField()),
            ],
        ),
    ]
