# Generated by Django 4.2 on 2025-07-11 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_technicianlocationassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilmoistureprediction',
            name='precipitation',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilmoistureprediction',
            name='prediction_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilmoistureprediction',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
