# Generated by Django 4.2 on 2025-07-11 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_soilmoistureprediction_precipitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilmoistureprediction',
            name='input_humidity',
        ),
        migrations.RemoveField(
            model_name='soilmoistureprediction',
            name='input_moisture',
        ),
        migrations.RemoveField(
            model_name='soilmoistureprediction',
            name='input_temperature',
        ),
        migrations.RemoveField(
            model_name='soilmoistureprediction',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='soilmoistureprediction',
            name='current_moisture',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soilmoistureprediction',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soilmoistureprediction',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soilmoistureprediction',
            name='precipitation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='soilmoistureprediction',
            name='prediction_for',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='soilmoistureprediction',
            name='status',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
