# Generated by Django 4.2 on 2025-07-14 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_soilmoistureprediction_input_humidity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSoilMoisturePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Location of the prediction', max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time of prediction')),
                ('current_moisture', models.FloatField(help_text='Current soil moisture percentage')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('precipitation', models.FloatField(default=0.0, help_text='Precipitation in mm')),
                ('predicted_category', models.CharField(help_text='Predicted moisture category', max_length=20)),
                ('predicted_moisture_value', models.FloatField(help_text='Predicted moisture value (%)')),
                ('confidence', models.FloatField(blank=True, help_text='Prediction confidence score', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last updated time')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterField(
            model_name='soilmoistureprediction',
            name='status',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddIndex(
            model_name='techniciansoilmoistureprediction',
            index=models.Index(fields=['location', 'timestamp'], name='authenticat_locatio_ab1c4d_idx'),
        ),
    ]
